import Head from 'next/head'
import Dashboard from '../components/Dashboard'
import Header from '../components/Header'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Gym planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Dashboard />
    </div>
  )
}
